In [1]:
import pandas as pd
import numpy as np
import os

In [12]:
def calculate_average_scores(directory):
    # Create an empty list to store average scores
    avg_scores_list = []
    
    for filename in os.listdir(directory):
        if filename.endswith('.csv'):
            filepath = os.path.join(directory, filename)
            
            # Read the CSV file into a DataFrame
            df = pd.read_csv(filepath)
            # Calculate average scores for each column
            avg_scores = {
                'filename': filename.rstrip('.csv'),
                'rouge_1_avg': round(df['rouge_1'].mean(), 2),
                'rouge_2_avg': round(df['rouge_2'].mean(), 2),
                'rouge_l_avg': round(df['rouge_l'].mean(), 2),
                'meteor_score_avg': round(df['meteor_score'].mean(), 2),
                'similarity_avg': round(df['similarity'].mean(), 2),
                'score_avg': round(df['score'].mean(), 2)
            }
            
            # Append average scores to the list
            avg_scores_list.append(avg_scores)
    
    # Convert the list of dictionaries to a DataFrame
    avg_scores_df = pd.DataFrame(avg_scores_list, columns=['filename', 'rouge_1_avg', 'rouge_2_avg', 'rouge_l_avg', 'meteor_score_avg', 'similarity_avg', 'score_avg'])
    
    return avg_scores_df

In [15]:
def count_score_values(directory):
    # Create an empty list to store score counts
    score_counts_list = []
    
    for filename in os.listdir(directory):
        if filename.endswith('.csv'):
            filepath = os.path.join(directory, filename)
            
            # Read the CSV file into a DataFrame
            df = pd.read_csv(filepath)
            # Count occurrences of each score value
            score_counts = {
                'filename': filename,
                '1': (df['score'] == 1).sum(),
                '2': (df['score'] == 2).sum(),
                '3': (df['score'] == 3).sum(),
                '4': (df['score'] == 4).sum(),
                '5': (df['score'] == 5).sum()
            }
            
            # Append score counts to the list
            score_counts_list.append(score_counts)
    
    # Convert the list of dictionaries to a DataFrame
    score_counts_df = pd.DataFrame(score_counts_list, columns=['filename', '1', '2', '3', '4', '5'])
    
    return score_counts_df

In [7]:
# Provide the directory containing the CSV files
directory = ''

In [13]:
# Call the function to calculate average scores
average_scores_dataframe = calculate_average_scores(directory)

In [14]:
average_scores_dataframe

,filename,rouge_1_avg,rouge_2_avg,rouge_l_avg,meteor_score_avg,similarity_avg,score_avg
0,llama3-70b_output,0.20,0.05,0.11,0.09,0.65,4.43
1,llama3-70b_output_mxbai_embedding,0.22,0.06,0.12,0.10,0.63,3.37
2,mixtral_8x7b_v1_output,0.19,0.05,0.11,0.09,0.62,4.59
3,mixtral_output_mxbai_embedding,0.23,0.06,0.13,0.12,0.62,4.02
4,openai_output,0.26,0.07,0.15,0.14,0.64,3.43
5,openai_output_with_mxbai,0.26,0.07,0.16,0.16,0.62,3.55

In [16]:
scores=count_score_values(directory)

In [17]:
scores

                                filename  1   2   3   4   5
0                  llama3-70b_output.csv  1   2   8  31  58
1  llama3-70b_output_mxbai_embedding.csv  0   3  61  32   4
2             mixtral_8x7b_v1_output.csv  2   1  16  48  32
3     mixtral_output_mxbai_embedding.csv  1   2  18  52  27
4                      openai_output.csv  0   1  58  36   4
5           openai_output_with_mxbai.csv  8  11  23  34  24

## Calculate Lift by RAG

In [2]:
def count_scores_by_type(directory):
    # Create an empty list to store score counts by type
    score_counts_by_type_list = []
    
    for filename in os.listdir(directory):
        if filename.endswith('.csv'):
            filepath = os.path.join(directory, filename)
            
            # Read the CSV file into a DataFrame
            df = pd.read_csv(filepath)
            
            # Group by 'type' and count the occurrences of each score for each type
            grouped = df.groupby('type')['score'].value_counts().unstack(fill_value=0).reset_index()
            grouped['filename'] = filename.rstrip('.csv')
            
            # Append each row to the list
            for _, row in grouped.iterrows():
                score_counts = {
                    'filename': row['filename'],
                    'type': row['type'],
                    'score_1': row.get(1, 0),
                    'score_2': row.get(2, 0),
                    'score_3': row.get(3, 0),
                    'score_4': row.get(4, 0),
                    'score_5': row.get(5, 0)
                }
                score_counts_by_type_list.append(score_counts)
    
    # Convert the list of dictionaries to a DataFrame
    score_counts_by_type_df = pd.DataFrame(score_counts_by_type_list, columns=['filename', 'type', 'score_1', 'score_2', 'score_3', 'score_4', 'score_5'])
    
    return score_counts_by_type_df

In [3]:
# Provide the directory containing the CSV files
directory = ''

In [4]:
score_by_type=count_scores_by_type(directory)

/tmp/ipykernel_61790/4277017457.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'score_1': row.get(1, 0),
/tmp/ipykernel_61790/4277017457.py:22: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'score_2': row.get(2, 0),
/tmp/ipykernel_61790/4277017457.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'score_3': row.get(3, 0),
/tmp/ipykernel_61790/4277017457.py:24: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'score_4': row.get(4, 0),
/tmp/ipykernel_61790/4277017457.py:25: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'score_5': row.get(5, 0)

In [5]:
score_by_type

,filename,type,score_1,score_2,score_3,score_4,score_5
0,llama3-70b_output,Anticipatory_bail,1,2,1,4,12
1,llama3-70b_output,Criminal,0,0,0,9,11
2,llama3-70b_output,Cyber_crime,0,0,3,7,10
3,llama3-70b_output,Juvenile,0,0,3,3,14
4,llama3-70b_output,Sex_crime,0,0,1,8,11
5,llama3-70b_output_mxbai_embedding,Anticipatory_bail,0,3,6,7,4
6,llama3-70b_output_mxbai_embedding,Criminal,0,0,11,9,0
7,llama3-70b_output_mxbai_embedding,Cyber_crime,0,0,14,6,0
8,llama3-70b_output_mxbai_embedding,Juvenile,0,0,15,5,0
9,llama3-70b_output_mxbai_embedding,Sex_crime,0,0,15,5,0
10,mixtral_8x7b_v1_output,Anticipatory_bail,1,1,1,10,7
11,mixtral_8x7b_v1_output,Criminal,0,0,4,9,7
12,mixtral_8x7b_v1_output,Cyber_crime,0,0,2,9,8
13,mixtral_8x7b_v1_output,Juvenile,1,0,4,10,5
14,mixtral_8x7b_v1_output,Sex_crime,0,0,5,10,5
15,mixtral_output_mxbai_embedding,Anticipatory_bail,1,2,6,6,5
16,mixtral_output_mxbai_embedding,Criminal,0,0,2,12,6
17,mixtral_output_mxbai_embedding,Cyber_crime,0,0,3,13,4
18,mixtral_output_mxbai_embedding,Juvenile,0,0,4,10,6
19,mixtral_output_mxbai_embedding,Sex_crime,0,0,3,11,6
20,openai_output,Anticipatory_bail,1,9,6,4,openai_output
21,openai_output,Criminal,0,13,7,0,openai_output
22,openai_output,Cyber_crime,0,15,5,0,openai_output
23,openai_output,Juvenile,0,10,10,0,openai_output
24,openai_output,Sex_crime,0,11,8,0,openai_output
25,openai_output_with_mxbai,Anticipatory_bail,0,4,7,5,4
26,openai_output_with_mxbai,Criminal,2,0,1,8,9
27,openai_output_with_mxbai,Cyber_crime,2,3,6,6,3
28,openai_output_with_mxbai,Juvenile,2,1,5,9,3
29,openai_output_with_mxbai,Sex_crime,2,3,4,6,5