In [3]:
import pandas as pd
import scipy.stats as stats

import numpy as np
from scipy import stats
# from statsmodels.stats.multicomp import pairwise_tukeyhsd, MultiComparison
import pandas as pd

In [2]:
base_path = ""

In [3]:
file_names = [
    'Davinci.csv',
    'LLama2-70b.csv',
    'Ada+Davinci.csv',
    'Instructor+Davinci.csv',
    'BM25+Davinci.csv',
    'Ada+LLama2-70b.csv',
    'Instructor+LLama2-70b.csv',
    'Ada+Flan-UL2.csv',
    'Instructor+Flan-UL2.csv'
]

In [4]:
mpnet_score_dict ={}
mpnet_scores_arrays = {}
for files in file_names:
    df = pd.read_csv(base_path+files, usecols=['mpnet_score'])  # Read only the mpnet_score column
    file_name = files.split('/')[-1][:-4]  # Extracting file name from the path
    print(file_name)
    mpnet_score_dict[file_name] = df
#     print(df)
    mpnet_scores_arrays[file_name + "_scores"] = np.array(df['mpnet_score'])

Davinci
LLama2-70b
Ada+Davinci
Instructor+Davinci
BM25+Davinci
Ada+LLama2-70b
Instructor+LLama2-70b
Ada+Flan-UL2
Instructor+Flan-UL2

In [6]:
df = pd.DataFrame(mpnet_scores_arrays)

# Initialize a DataFrame for p-values
p_values = pd.DataFrame(index=df.columns, columns=df.columns)

# Calculate p-values
for model1 in df.columns:
    for model2 in df.columns:
        if model1 != model2:
            _, p_value = stats.ttest_rel(df[model1], df[model2])
            p_values.at[model1, model2] = p_value

# Mask upper triangle of the DataFrame
mask = np.tril(np.ones_like(p_values, dtype=bool))
lower_tri_p_values = p_values.where(mask)

# Optional: Adjust for multiple comparisons
adjusted_p_values = lower_tri_p_values.apply(lambda x: x * (len(df.columns) - 1))
adjusted_p_values = adjusted_p_values.clip(upper=1.0)

# Round to four decimal places and replace NaN with '-'
lower_tri_p_values = lower_tri_p_values.round(4).fillna('-')
adjusted_p_values = adjusted_p_values.round(4).fillna('-')

# Display lower triangular p-values
# print("Lower Triangular P-Values:\n", lower_tri_p_values)
# print("\nLower Triangular Adjusted P-Values:\n", adjusted_p_values)

In [7]:
pd.options.display.float_format = '{:.4f}'.format

In [8]:
lower_tri_p_values

,Davinci_scores,LLama2-70b_scores,Ada+Davinci_scores,Instructor+Davinci_scores,BM25+Davinci_scores,Ada+LLama2-70b_scores,Instructor+LLama2-70b_scores,Ada+Flan-UL2_scores,Instructor+Flan-UL2_scores
Davinci_scores,-,-,-,-,-,-,-,-,-
LLama2-70b_scores,0.0786,-,-,-,-,-,-,-,-
Ada+Davinci_scores,0.2527,0.0366,-,-,-,-,-,-,-
Instructor+Davinci_scores,0.4387,0.0948,0.4596,-,-,-,-,-,-
BM25+Davinci_scores,0.0037,0.0006,0.0116,0.0070,-,-,-,-,-
Ada+LLama2-70b_scores,0.7206,0.1237,0.2089,0.3715,0.0035,-,-,-,-
Instructor+LLama2-70b_scores,0.4678,0.2900,0.1333,0.2627,0.0016,0.7035,-,-,-
Ada+Flan-UL2_scores,0.0000,0.0000,0.0000,0.0000,0.0002,0.0000,0.0000,-,-
Instructor+Flan-UL2_scores,0.0000,0.0000,0.0000,0.0000,0.0044,0.0000,0.0000,0.2451,-

In [9]:
adjusted_p_values

,Davinci_scores,LLama2-70b_scores,Ada+Davinci_scores,Instructor+Davinci_scores,BM25+Davinci_scores,Ada+LLama2-70b_scores,Instructor+LLama2-70b_scores,Ada+Flan-UL2_scores,Instructor+Flan-UL2_scores
Davinci_scores,-,-,-,-,-,-,-,-,-
LLama2-70b_scores,0.6286,-,-,-,-,-,-,-,-
Ada+Davinci_scores,1.0000,0.2927,-,-,-,-,-,-,-
Instructor+Davinci_scores,1.0000,0.7580,1.0000,-,-,-,-,-,-
BM25+Davinci_scores,0.0297,0.0045,0.0925,0.0560,-,-,-,-,-
Ada+LLama2-70b_scores,1.0000,0.9893,1.0000,1.0000,0.0279,-,-,-,-
Instructor+LLama2-70b_scores,1.0000,1.0000,1.0000,1.0000,0.0125,1.0000,-,-,-
Ada+Flan-UL2_scores,0.0000,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,-,-
Instructor+Flan-UL2_scores,0.0000,0.0000,0.0000,0.0000,0.0349,0.0000,0.0000,1.0000,-

## On Test -2

In [11]:
base_path = ""

In [20]:
file_names = [
    'llama3-70b_output.csv',
    'llama3-70b_output_mxbai_embedding.csv',
    'mixtral_8x7b_v1_output.csv',
    'mixtral_output_mxbai_embedding.csv',
    'openai_gpt_3.5_turbo_output.csv',
    'openai_gpt_3.5_turbo_output_with_mxbai.csv'   
]

In [21]:
mpnet_score_dict ={}
mpnet_scores_arrays = {}
for files in file_names:
    df = pd.read_csv(base_path+files, usecols=['similarity'])  # Read only the mpnet_score column
    file_name = files.split('/')[-1][:-4]  # Extracting file name from the path
    print(file_name)
    mpnet_score_dict[file_name] = df
#     print(df)
    mpnet_scores_arrays[file_name + "_scores"] = np.array(df['similarity'])

llama3-70b_output
llama3-70b_output_mxbai_embedding
mixtral_8x7b_v1_output
mixtral_output_mxbai_embedding
openai_gpt_3.5_turbo_output
openai_gpt_3.5_turbo_output_with_mxbai

In [22]:
mpnet_scores_arrays

{'llama3-70b_output_scores': array([0.7695977 , 0.7058103 , 0.706041  , 0.7832663 , 0.61711264,
        0.66942984, 0.46012843, 0.55235094, 0.84580237, 0.77965236,
        0.40800574, 0.8287064 , 0.70746344, 0.36264247, 0.5508798 ,
        0.52406573, 0.23050101, 0.611987  , 0.5380052 , 0.68928075,
        0.7065444 , 0.8611472 , 0.8151203 , 0.8226451 , 0.7802834 ,
        0.41394538, 0.6448332 , 0.7528795 , 0.7965733 , 0.6347495 ,
        0.7096064 , 0.4362694 , 0.73280525, 0.80086374, 0.2511061 ,
        0.69481367, 0.5987727 , 0.09478025, 0.28772652, 0.37110206,
        0.51332164, 0.7398959 , 0.72799635, 0.7601384 , 0.77536213,
        0.91723186, 0.67876357, 0.827119  , 0.37051737, 0.80402595,
        0.42406952, 0.55348516, 0.60386986, 0.6606984 , 0.6307134 ,
        0.7064702 , 0.7892495 , 0.6203464 , 0.55636936, 0.54065293,
        0.8044897 , 0.6145096 , 0.6474679 , 0.711814  , 0.58515745,
        0.5711946 , 0.8745595 , 0.87498796, 0.5955061 , 0.90687805,
        0.9253861 , 0.59166217, 0.47905415, 0.45364246, 0.6505816 ,
        0.7668466 , 0.59146   , 0.52077866, 0.6459287 , 0.6213702 ,
        0.6670385 , 0.82397246, 0.6106684 , 0.7882672 , 0.83431756,
        0.59159863, 0.7540881 , 0.8501719 , 0.37650147, 0.80060774,
        0.7540775 , 0.83292955, 0.6658103 , 0.7563627 , 0.6440109 ,
        0.57711434, 0.6554979 , 0.2981739 , 0.6434629 , 0.4761033 ]),
 'llama3-70b_output_mxbai_embedding_scores': array([0.7735575 , 0.76505464, 0.7000873 , 0.6832195 , 0.59446293,
        0.52578175, 0.46471938, 0.5643054 , 0.8110563 , 0.81308776,
        0.47539812, 0.83133   , 0.71423364, 0.42696565, 0.5324524 ,
        0.5321981 , 0.46439087, 0.6122142 , 0.50452256, 0.6501631 ,
        0.7208601 , 0.866444  , 0.7456886 , 0.7513181 , 0.74793047,
        0.38119215, 0.5742363 , 0.68773466, 0.82350487, 0.6352915 ,
        0.6051161 , 0.27565733, 0.78289515, 0.82268816, 0.25505593,
        0.7041144 , 0.59234846, 0.07406665, 0.2142984 , 0.3659764 ,
        0.47570837, 0.72512597, 0.7310896 , 0.7194723 , 0.7028155 ,
        0.926153  , 0.6254408 , 0.4183507 , 0.3695231 , 0.68930995,
        0.42928433, 0.5907605 , 0.60725474, 0.6644528 , 0.5697003 ,
        0.63475   , 0.8920181 , 0.6007653 , 0.59053355, 0.45805266,
        0.8244804 , 0.6607277 , 0.6348286 , 0.66999525, 0.58020324,
        0.5595861 , 0.82419455, 0.75044185, 0.54857713, 0.9198748 ,
        0.93903613, 0.6128217 , 0.57855666, 0.3523538 , 0.65752244,
        0.720573  , 0.5596613 , 0.48207688, 0.6002366 , 0.5916772 ,
        0.6035521 , 0.8055364 , 0.6993107 , 0.7742426 , 0.8116495 ,
        0.5995016 , 0.7481271 , 0.8629124 , 0.39688826, 0.7408626 ,
        0.7587984 , 0.8083933 , 0.6735133 , 0.7456528 , 0.6211417 ,
        0.5174572 , 0.687342  , 0.31367287, 0.70383716, 0.3885262 ]),
 'mixtral_8x7b_v1_output_scores': array([ 0.8407074 ,  0.6620331 ,  0.6079931 ,  0.794761  ,  0.54345757,
         0.6202057 ,  0.41908035,  0.6241986 ,  0.9268628 ,  0.78693134,
         0.49950072,  0.8419723 ,  0.5756074 ,  0.35636717,  0.5984121 ,
        -0.01374219,  0.51099163,  0.6016448 ,  0.4967631 ,  0.61426574,
         0.7685533 ,  0.77331954,  0.90520996,  0.8051073 ,  0.7349512 ,
         0.30107838,  0.65197814,  0.7385558 ,  0.76561105,  0.5928282 ,
         0.69086325,  0.3437336 ,  0.53388643,  0.8229293 ,  0.26076555,
         0.7147381 ,  0.62179154,  0.10472073,  0.29905698,  0.36322582,
         0.61431795,  0.82978785,  0.63392675,  0.7067961 ,  0.6816188 ,
         0.81805104,  0.68679637,  0.3829061 ,  0.3066039 ,  0.753632  ,
         0.47315556,  0.5380869 ,  0.59676754,  0.68569225,  0.6065606 ,
         0.65649897,  0.7784032 ,  0.7106858 ,  0.6542441 ,  0.570957  ,
         0.7856075 ,  0.5294659 ,  0.6358755 ,  0.64582235,  0.52080125,
         0.5071158 ,  0.8471122 ,  0.7950938 ,  0.5914761 ,  0.9570427 ,
         0.86390257,  0.49462327,  0.5275552 ,  0.42636606,  0.64117616,
         0.7446148 ,  0.38098264,  0.6127025 ,  0.69157344,  0.63142896,
         0.64502597,  0.7879963 ,  0.62053967,  0.7652298 ,  0.8339441 ,
         0.59800094,  0.7002665 ,  0.7823682 ,  0.2676195 ,  0.7694579 ,
         0.7207757 ,  0.81889635,  0.65821356,  0.6890925 ,  0.5964611 ,
         0.61615485,  0.6732743 ,  0.35621873,  0.6817862 ,  0.47600055]),
 'mixtral_output_mxbai_embedding_scores': array([0.7640599 , 0.79409635, 0.7350282 , 0.65200925, 0.6756759 ,
        0.6314912 , 0.41649455, 0.43591607, 0.8640761 , 0.77889115,
        0.5497866 , 0.738198  , 0.75719476, 0.41815665, 0.55906564,
        0.5266133 , 0.50812024, 0.6509036 , 0.48421207, 0.6035678 ,
        0.6695404 , 0.79566646, 0.65147847, 0.8476092 , 0.75325716,
        0.32459146, 0.5828428 , 0.7488308 , 0.8360291 , 0.59596545,
        0.6804178 , 0.2784055 , 0.7461973 , 0.72539943, 0.2720592 ,
        0.80914557, 0.54531145, 0.11636238, 0.3944617 , 0.4158212 ,
        0.40900192, 0.70248884, 0.65004915, 0.6513311 , 0.6557341 ,
        0.9182378 , 0.54302436, 0.47101098, 0.30955377, 0.71862847,
        0.40859997, 0.40806168, 0.43611163, 0.59986013, 0.71466124,
        0.6581828 , 0.80229336, 0.6237853 , 0.65616655, 0.54001427,
        0.8183498 , 0.62788594, 0.5781501 , 0.72102404, 0.5488575 ,
        0.58451855, 0.8630198 , 0.84840024, 0.5645298 , 0.9108571 ,
        0.90273833, 0.64037114, 0.44436884, 0.32843277, 0.5823912 ,
        0.6608473 , 0.4839369 , 0.42380208, 0.56310195, 0.48542666,
        0.58148277, 0.7335337 , 0.71260643, 0.69070464, 0.8713992 ,
        0.6204005 , 0.75025874, 0.87654805, 0.34241647, 0.6660229 ,
        0.8084303 , 0.64956075, 0.62984765, 0.74822426, 0.5963719 ,
        0.56606543, 0.7304852 , 0.3201268 , 0.57052237, 0.31007823]),
 'openai_gpt_3.5_turbo_output_scores': array([0.7790796 , 0.7665166 , 0.8281573 , 0.7686912 , 0.6526967 ,
        0.6575458 , 0.4224198 , 0.44826046, 0.8458296 , 0.85127366,
        0.2170665 , 0.82797635, 0.7919923 , 0.46286342, 0.58447474,
        0.441391  , 0.4813866 , 0.63346887, 0.48461577, 0.66400903,
        0.6954343 , 0.89923316, 0.6332918 , 0.8883388 , 0.7502937 ,
        0.28879595, 0.6595125 , 0.7340701 , 0.79212576, 0.6231725 ,
        0.6891274 , 0.2677329 , 0.7612219 , 0.7680075 , 0.28308928,
        0.7188529 , 0.45614594, 0.07179558, 0.49451083, 0.41452903,
        0.3691476 , 0.74876755, 0.68649876, 0.73342264, 0.83881676,
        0.9172444 , 0.8277764 , 0.8133535 , 0.3433241 , 0.82539177,
        0.3593621 , 0.4873537 , 0.4658172 , 0.7372287 , 0.61738765,
        0.73524785, 0.75084686, 0.6704659 , 0.60351825, 0.4707631 ,
        0.84234273, 0.66593367, 0.74252796, 0.64872694, 0.4728049 ,
        0.50742835, 0.87138855, 0.8421515 , 0.5348291 , 0.90816396,
        0.94943506, 0.514951  , 0.6465032 , 0.36702755, 0.55939746,
        0.63239175, 0.50342983, 0.45545077, 0.4992312 , 0.49498263,
        0.68305963, 0.801356  , 0.74566776, 0.8044505 , 0.8088547 ,
        0.53067356, 0.739188  , 0.8280987 , 0.38696912, 0.841108  ,
        0.62834835, 0.6703978 , 0.68888295, 0.7325306 , 0.7360967 ,
        0.5836633 , 0.72746843, 0.3369155 , 0.6790995 , 0.41748443]),
 'openai_gpt_3.5_turbo_output_with_mxbai_scores': array([0.7854148 , 0.80004877, 0.83831745, 0.6562232 , 0.62860936,
        0.78882396, 0.4449176 , 0.46489912, 0.87410307, 0.735245  ,
        0.43343553, 0.74512964, 0.7100133 , 0.39134958, 0.6108693 ,
        0.44494998, 0.51343966, 0.62645483, 0.54871523, 0.5403104 ,
        0.72225356, 0.82660925, 0.7855015 , 0.7821253 , 0.7199233 ,
        0.35138094, 0.6338966 , 0.7294014 , 0.7012686 , 0.6510039 ,
        0.62882715, 0.23542294, 0.6800044 , 0.79980934, 0.36112785,
        0.68726283, 0.49066   , 0.11135673, 0.31589037, 0.43125102,
        0.06023813, 0.73670965, 0.74690276, 0.68134636, 0.68688965,
        0.91952217, 0.6687174 , 0.8366118 , 0.2053705 , 0.6797524 ,
        0.45128632, 0.47859532, 0.37859288, 0.79468834, 0.6394175 ,
        0.69939035, 0.8180809 , 0.5692752 , 0.5921551 , 0.4428355 ,
        0.79216033, 0.69682527, 0.6391019 , 0.4741131 , 0.54966635,
        0.76565474, 0.8010243 , 0.83736193, 0.4488657 , 0.9201703 ,
        0.895983  , 0.49939626, 0.41765565, 0.41181913, 0.3956526 ,
        0.67476   , 0.48605525, 0.38363478, 0.52311575, 0.5240432 ,
        0.6186755 , 0.833231  , 0.6862763 , 0.8171549 , 0.8168868 ,
        0.56126356, 0.7495138 , 0.8470301 , 0.45830652, 0.7480352 ,
        0.8522131 , 0.74121976, 0.7054208 , 0.7132935 , 0.5999656 ,
        0.6479863 , 0.7044916 , 0.36735126, 0.6390605 , 0.4131904 ])}

In [23]:
df = pd.DataFrame(mpnet_scores_arrays)

# Initialize a DataFrame for p-values
p_values = pd.DataFrame(index=df.columns, columns=df.columns)

# Calculate p-values
for model1 in df.columns:
    for model2 in df.columns:
        if model1 != model2:
            _, p_value = stats.ttest_rel(df[model1], df[model2])
            p_values.at[model1, model2] = p_value

# Mask upper triangle of the DataFrame
mask = np.tril(np.ones_like(p_values, dtype=bool))
lower_tri_p_values = p_values.where(mask)

# Optional: Adjust for multiple comparisons
adjusted_p_values = lower_tri_p_values.apply(lambda x: x * (len(df.columns) - 1))
adjusted_p_values = adjusted_p_values.clip(upper=1.0)

# Round to four decimal places and replace NaN with '-'
lower_tri_p_values = lower_tri_p_values.round(4).fillna('-')
adjusted_p_values = adjusted_p_values.round(4).fillna('-')

# Display lower triangular p-values
# print("Lower Triangular P-Values:\n", lower_tri_p_values)
# print("\nLower Triangular Adjusted P-Values:\n", adjusted_p_values)

In [24]:
pd.options.display.float_format = '{:.4f}'.format

In [25]:
lower_tri_p_values

,llama3-70b_output_scores,llama3-70b_output_mxbai_embedding_scores,mixtral_8x7b_v1_output_scores,mixtral_output_mxbai_embedding_scores,openai_gpt_3.5_turbo_output_scores,openai_gpt_3.5_turbo_output_with_mxbai_scores
llama3-70b_output_scores,-,-,-,-,-,-
llama3-70b_output_mxbai_embedding_scores,0.0101,-,-,-,-,-
mixtral_8x7b_v1_output_scores,0.0169,0.5567,-,-,-,-
mixtral_output_mxbai_embedding_scores,0.0005,0.0666,0.5057,-,-,-
openai_gpt_3.5_turbo_output_scores,0.1979,0.4308,0.2851,0.0275,-,-
openai_gpt_3.5_turbo_output_with_mxbai_scores,0.0075,0.4009,0.8119,0.6591,0.0809,-

In [9]:
adjusted_p_values

,Davinci_scores,LLama2-70b_scores,Ada+Davinci_scores,Instructor+Davinci_scores,BM25+Davinci_scores,Ada+LLama2-70b_scores,Instructor+LLama2-70b_scores,Ada+Flan-UL2_scores,Instructor+Flan-UL2_scores
Davinci_scores,-,-,-,-,-,-,-,-,-
LLama2-70b_scores,0.6286,-,-,-,-,-,-,-,-
Ada+Davinci_scores,1.0000,0.2927,-,-,-,-,-,-,-
Instructor+Davinci_scores,1.0000,0.7580,1.0000,-,-,-,-,-,-
BM25+Davinci_scores,0.0297,0.0045,0.0925,0.0560,-,-,-,-,-
Ada+LLama2-70b_scores,1.0000,0.9893,1.0000,1.0000,0.0279,-,-,-,-
Instructor+LLama2-70b_scores,1.0000,1.0000,1.0000,1.0000,0.0125,1.0000,-,-,-
Ada+Flan-UL2_scores,0.0000,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,-,-
Instructor+Flan-UL2_scores,0.0000,0.0000,0.0000,0.0000,0.0349,0.0000,0.0000,1.0000,-